// <auto-generated />
namespace Task_Managment_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddPriortyPropertyToComments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPriortyPropertyToComments));
        
        string IMigrationMetadata.Id
        {
            get { return "202105261841299_AddPriortyPropertyToComments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
